spring.application.name=backend
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mentecolmena

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Configuración del modelo gratuito de Gemini IA
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-1.5-flash

